name: budget_map
description: "A Budget Management App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: any
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/icon.png
  image_dark: assets/icon_inverted.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/icon.png
    - assets/icon_inverted.png
